services:
  postgres_test:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  user_app:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_test:5432/db
    ports:
      - 3000:3000
    depends_on:
      - postgres_test
  